---
- name: Playbook para hacer el deploy de la aplicación web WordPress
  hosts: frontend1,frontend2
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: Instalar PHP y dependencias
      apt:
        name:
          - php
          - php-cli
          - php-mysql
          - php-xml
          - php-mbstring
        state: present

    - name: Descargar la utilidad WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: 0755

    - name: Detener el servidor web Apache antes de eliminar archivos
      service:
        name: apache2
        state: stopped

    - name: Verificar si los archivos de WordPress ya existen
      stat:
        path: /var/www/html/wp-config.php
      register: wordpress_files

    - name: Eliminar archivos existentes de WordPress forzadamente si existe
      command:
        cmd: rm -rf /var/www/html/*
      when: wordpress_files.stat.exists == true

    - name: Crear directorio vacío para WordPress
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Descargar el código fuente de WordPress solo si no está presente
      command:
        cmd: wp core download --locale="{{ wordpress.locale }}" --path=/var/www/html --allow-root
      when: wordpress_files.stat.exists == false

    - name: Eliminar archivo wp-config.php si existe
      command:
        cmd: rm -f /var/www/html/wp-config.php
      ignore_errors: yes

    - name: Crear el archivo wp-config.php
      command: |
        wp config create \
          --dbname="{{ db.name }}" \
          --dbuser="{{ db.user }}" \
          --dbpass="{{ db.password }}" \
          --dbhost="{{ ip.backend }}" \
          --path=/var/www/html \
          --allow-root

    - name: Instalar WordPress
      command: |
        wp core install \
          --url="{{ certbot.domain }}" \
          --title="{{ wordpress.title }}" \
          --admin_user="{{ wordpress.admin_user }}" \
          --admin_password="{{ wordpress.admin_pass }}" \
          --admin_email="{{ wordpress.admin_email }}" \
          --path=/var/www/html \
          --allow-root

    - name: Modificar los permisos del directorio /var/www/html
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
        mode: '0755'

    - name: Iniciar el servidor web Apache después de la instalación
      service:
        name: apache2
        state: started
